symbols_nobitex_IR=['BTCIRT','ETHIRT','LTCIRT','USDTIRT','XRPIRT','BCHIRT','BNBIRT','EOSIRT','XLMIRT','ETCIRT','TRXIRT','DOGEIRT','UNIIRT','DAIIRT','LINKIRT','DOTIRT','AAVEIRT','ADAIRT','SHIBIRT','FTMIRT','MATICIRT','AXSIRT','MANAIRT','SANDIRT','AVAXIRT','MKRIRT','GMTIRT','USDCIRT']
symbols_nobitex_USDT=['BTCUSDT','ETHUSDT','LTCUSDT','XRPUSDT','BCHUSDT','BNBUSDT','EOSUSDT','XLMUSDT','ETCUSDT','TRXUSDT','PMNUSDT','DOGEUSDT','UNIUSDT','DAIUSDT','LINKUSDT','DOTUSDT','AAVEUSDT','ADAUSDT','SHIBUSDT','FTMUSDT','MATICUSDT','AXSUSDT','MANAUSDT','SANDUSDT','AVAXUSDT','MKRUSDT','GMTUSDT','USDCUSDT']
symbols_nobitex=symbols_nobitex_IR+symbols_nobitex_USDT
print(symbols_nobitex)
